export const mockData = [
  {
    id: 1,
    name: "All Out 45ml",
    sku_code: "GHJ/456",
    item_group: "Packaging Material",
    available_stock: "20 pcs",
    min_stock_level: "2 pcs",
    reorder_level: 3,
    last_purchased: "2023-04-12",
    supplier: "Venus Store",
    stock_status: "Available",
    status: true,
  },
  {
    id: 2,
    name: "Harpic 500ml",
    sku_code: "HRP/789",
    item_group: "Refill & Cleaner",
    available_stock: "5 kg",
    min_stock_level: "5 kg",
    reorder_level: 5,
    last_purchased: "2023-03-22",
    supplier: "Metro Distributors",
    stock_status: "REORDER ITEM",
    status: false,
  },
  {
    id: 3,
    name: "Lizol Lavender 1L",
    sku_code: "LZL/001",
    item_group: "Surface Cleaner",
    available_stock: "15 pcs",
    min_stock_level: "10 pcs",
    reorder_level: 6,
    last_purchased: "2023-05-01",
    supplier: "Clean Supplies Co.",
    stock_status: "STOCK OK",
    status: true,
  },
];
