export const indentData = [
  {
    id: 1,
    date: "16/05/2025 10:15 AM",
    indent_no: "IND/2025-26/25",
    department: "Operations",
    priority: "High",
    store_location: "Plant",
    status: "OPEN",
    raised_by: "Rajeev Singh",
    raised_on: "16/05/2025",
    indent_requirement: [
      {
        item: "Tetra Pack",
        expected_by: "25/05/2025",
        vendor: "RK Traders",
        shape: "Thin Shape",
        required_qty: 10000,
        available_qty: 12000,
      },
      {
        item: "Plastic Pouches",
        expected_by: "25/05/2025",
        vendor: "RK Traders",
        shape: "Thin Shape",
        required_qty: 5000,
        available_qty: 9000,
      },
      {
        item: "Skrink Wraps",
        expected_by: "25/05/2025",
        vendor: "RK Traders",
        shape: "Thin Shape",
        required_qty: 800,
        available_qty: 600,
      },
      {
        item: "Glass Bottles",
        expected_by: "25/05/2025",
        vendor: "RK Traders",
        shape: "Thin Shape",
        required_qty: 5000,
        available_qty: 4000,
      },
    ],
  },
  {
    id: 2,
    date: "10/05/2025 09:15 AM",
    indent_no: "IND/2025-26/24",
    department: "Productions",
    priority: "High",
    store_location: "Delhi",
    status: "OPEN",
    raised_by: "Suresh Tiwari",
    raised_on: "10/05/2025",
    indent_requirement: [
      {
        item: "Packaging Box",
        expected_by: "20/05/2025",
        vendor: "Om Packaging",
        shape: "Square",
        required_qty: 3000,
        available_qty: 5000,
      },
      {
        item: "Bottle Caps",
        expected_by: "20/05/2025",
        vendor: "Cap King",
        shape: "Round",
        required_qty: 2000,
        available_qty: 1500,
      },
      {
        item: "Carton Sheets",
        expected_by: "22/05/2025",
        vendor: "Paper Traders",
        shape: "Flat",
        required_qty: 4000,
        available_qty: 3500,
      },
      {
        item: "Bottle Caps",
        expected_by: "20/05/2025",
        vendor: "Cap King",
        shape: "Round",
        required_qty: 2000,
        available_qty: 1500,
      },
    ],
  },
  {
    id: 3,
    date: "05/03/2025 10:36 AM",
    indent_no: "IND/2025-26/23",
    department: "Operations",
    priority: "Medium",
    store_location: "Noida",
    status: "APPROVED",
    raised_by: "Arvind Singh",
    raised_on: "05/03/2025",
    indent_requirement: [
      {
        item: "Glue Tubes",
        expected_by: "10/03/2025",
        vendor: "StickWell",
        shape: "Tube",
        required_qty: 1500,
        available_qty: 1800,
      },
      {
        item: "Paper Rolls",
        expected_by: "12/03/2025",
        vendor: "Paper Mart",
        shape: "Roll",
        required_qty: 10000,
        available_qty: 9500,
      },
    ],
  },
  {
    id: 4,
    date: "04/02/2025 11:45 AM",
    indent_no: "IND/2025-26/21",
    department: "Productions",
    priority: "Low",
    store_location: "Delhi",
    status: "APPROVED",
    raised_by: "Suresh Tiwari",
    raised_on: "04/02/2025",
    indent_requirement: [
      {
        item: "Ink Bottles",
        expected_by: "15/02/2025",
        vendor: "ColorX",
        shape: "Bottle",
        required_qty: 1000,
        available_qty: 1200,
      },
      {
        item: "Stickers",
        expected_by: "14/02/2025",
        vendor: "Label Hub",
        shape: "Rectangular",
        required_qty: 2000,
        available_qty: 2500,
      },
      {
        item: "Adhesive Tape",
        expected_by: "16/02/2025",
        vendor: "TapeCo",
        shape: "Roll",
        required_qty: 800,
        available_qty: 700,
      },
    ],
  },
  // You can repeat similar patterns for id: 5 to id: 8
];
