export const inventoryData = [
  {
    id: 1,
    productName: "Tetra Packs",
    skuCode: "PM00456",
    uom: "pcs.",
    openingStock: 7000,
    stockIn: 3500,
    stockOut: 500,
    currentStock: 10000,
    reorderLevel: 5000,
    minLevel: 4000,
    status: "Available",
  },
  {
    id: 2,
    productName: "Plastic Pouches",
    skuCode: "PM00408",
    uom: "pcs.",
    openingStock: 40000,
    stockIn: 14000,
    stockOut: 4000,
    currentStock: 50000,
    reorderLevel: 10000,
    minLevel: 6000,
    status: "Available",
  },
  {
    id: 3,
    productName: "Shrink Wraps",
    skuCode: "PM00713",
    uom: "pcs.",
    openingStock: 400,
    stockIn: 500,
    stockOut: 100,
    currentStock: 800,
    reorderLevel: 1000,
    minLevel: 400,
    status: "Reorder",
  },
  {
    id: 4,
    productName: "Salt",
    skuCode: "AI00120",
    uom: "kg.",
    openingStock: 200,
    stockIn: 250,
    stockOut: 50,
    currentStock: 400,
    reorderLevel: 300,
    minLevel: 200,
    status: "Available",
  },
  {
    id: 5,
    productName: "Glass Bottles",
    skuCode: "PM00725",
    uom: "pcs.",
    openingStock: 3000,
    stockIn: 2500,
    stockOut: 500,
    currentStock: 5000,
    reorderLevel: 7000,
    minLevel: 6000,
    status: "SOS",
  },
];

export const stockInReportData = [
  {
    id: 1,
    transaction_id: "RS/2025-26/25",
    product_name: "Tetra Packs",
    sku_code: "SKU-TP-001",
    quantity_received: "3500",
    source: "PO",
    vendor_name: "Shyam Traders",
    received_by: "Rajesh Kumar",
    remarks: "Received as per PO #PO-2024-233, Batch-34",
    date: "16/05/2025",
  },
  {
    id: 2,
    transaction_id: "RS/2025-26/26",
    product_name: "Plastic Bottles",
    sku_code: "SKU-PB-002",
    quantity_received: "5000",
    source: "PO",
    vendor_name: "Global Containers",
    received_by: "Sunita Sharma",
    remarks: "Verified with batch BT-456",
    date: "18/05/2025",
  },
  {
    id: 3,
    transaction_id: "RS/2025-26/27",
    product_name: "Cardboard Boxes",
    sku_code: "SKU-CB-003",
    quantity_received: "4500",
    source: "Manual",
    vendor_name: "Om Packaging",
    received_by: "Rajeev Singh",
    remarks: "Urgent requirement received",
    date: "20/05/2025",
  },
  {
    id: 4,
    transaction_id: "RS/2025-26/28",
    product_name: "Glass Jars",
    sku_code: "SKU-GJ-004",
    quantity_received: "3000",
    source: "PO",
    vendor_name: "Crystal Ware",
    received_by: "Kiran Patel",
    remarks: "Damaged items replaced",
    date: "22/05/2025",
  },
  {
    id: 5,
    transaction_id: "RS/2025-26/29",
    product_name: "Shrink Wrap",
    sku_code: "SKU-SW-005",
    quantity_received: "1200",
    source: "PO",
    vendor_name: "Secure Wrap Co.",
    received_by: "Anil Yadav",
    remarks: "Extra stock received",
    date: "24/05/2025",
  },

];





export const stockOutReportData = [
  {
    id: 1,
    transaction_id: "RS/2025-26/25",
    date: "16/05/2025",
    product_name: "Tetra Packs",
    quantity_issued: "3500",
    issued_to: "Production",
    purpose: "Batch Packing",
    vendor_name: "Shyam Traders",
    issued_by: "Rajesh Kumar",
    remarks: "Urgent",
  },
  {
    id: 2,
    transaction_id: "RS/2025-26/26",
    date: "17/05/2025",
    product_name: "Plastic Bottles",
    quantity_issued: "4200",
    issued_to: "Packaging",
    purpose: "Bottling Line",
    vendor_name: "Global Containers",
    issued_by: "Sunita Sharma",
    remarks: "On schedule",
  },
  {
    id: 3,
    transaction_id: "RS/2025-26/27",
    date: "18/05/2025",
    product_name: "Cardboard Boxes",
    quantity_issued: "5000",
    issued_to: "Shipping",
    purpose: "Dispatch Packing",
    vendor_name: "Om Packaging",
    issued_by: "Rajeev Singh",
    remarks: "Handle with care",
  },
  {
    id: 4,
    transaction_id: "RS/2025-26/28",
    date: "19/05/2025",
    product_name: "Glass Jars",
    quantity_issued: "2800",
    issued_to: "Production",
    purpose: "Refill Line",
    vendor_name: "Crystal Ware",
    issued_by: "Kiran Patel",
    remarks: "Fragile items",
  },
  {
    id: 5,
    transaction_id: "RS/2025-26/29",
    date: "20/05/2025",
    product_name: "Shrink Wrap",
    quantity_issued: "1500",
    issued_to: "Packaging",
    purpose: "Wrapping",
    vendor_name: "Secure Wrap Co.",
    issued_by: "Anil Yadav",
    remarks: "Urgent requirement",
  },

];



export const indentReportData = [
  {
    id: 1,
    indent_number: "IND/2025-1001",
    date: "01/06/2025",
    raised_by: "Rajesh Kumar",
    department: "Production",
    product_name: "Tetra Packs",
    request_quantity: 5000,
    approved_quantity: 4500,
    indent_status: "Approved",
    linked_po: "PO/2025-2001",
    remark: "Urgent requirement",
  },
  {
    id: 2,
    indent_number: "IND/2025-1002",
    date: "03/06/2025",
    raised_by: "Sunita Sharma",
    department: "Packaging",
    product_name: "Plastic Bottles",
    request_quantity: 3000,
    approved_quantity: 3000,
    indent_status: "Pending",
    linked_po: "PO/2025-2002",
    remark: "Regular stock",
  },
  {
    id: 3,
    indent_number: "IND/2025-1003",
    date: "04/06/2025",
    raised_by: "Mohit Verma",
    department: "Quality",
    product_name: "Label Stickers",
    request_quantity: 1500,
    approved_quantity: 1500,
    indent_status: "Rejected",
    linked_po: "PO/2025-2003",
    remark: "Batch #Q123",
  },
  {
    id: 4,
    indent_number: "IND/2025-1004",
    date: "05/06/2025",
    raised_by: "Priya Singh",
    department: "Production",
    product_name: "Cardboard Boxes",
    request_quantity: 4000,
    approved_quantity: 3500,
    indent_status: "Partially Approved",
    linked_po: "PO/2025-2004",
    remark: "Supplier delay expected",
  },
  {
    id: 5,
    indent_number: "IND/2025-1005",
    date: "06/06/2025",
    raised_by: "Ravi Sharma",
    department: "Maintenance",
    product_name: "Sealing Tape",
    request_quantity: 1200,
    approved_quantity: 1200,
    indent_status: "Approved",
    linked_po: "PO/2025-2005",
    remark: "Stock replenishment",
  },
];


export const purchaseOrderReportData = [
  {
    id: 1,
    po_number: "PO/2025-26/001",
    po_date: "01/05/2025",
    vendor_name: "Shyam Traders",
    linked_indents: "IND013, IND017",
    delivery_status: "Pending",
    po_status: "Approved",
    total_amount: 125000,
    download_pos: "PO_001.pdf",
  },
  {
    id: 2,
    po_number: "PO/2025-26/002",
    po_date: "03/05/2025",
    vendor_name: "Global Containers",
    linked_indents: "IND014",
    delivery_status: "Pending",
    po_status: "Completed",
    total_amount: 88000,
    download_pos: "PO_002.pdf",
  },
  {
    id: 3,
    po_number: "PO/2025-26/003",
    po_date: "05/05/2025",
    vendor_name: "Om Packaging",
    linked_indents: "IND015, IND2618",
    delivery_status: "Partially Received",
    po_status: "Partially Completed",
    total_amount: 154500,
    download_pos: "PO_003.pdf",
  },
  {
    id: 4,
    po_number: "PO/2025-26/004",
    po_date: "08/05/2025",
    vendor_name: "Crystal Ware",
    linked_indents: "IND0016",
    delivery_status: "Pending",
    po_status: "Pending",
    total_amount: 43200,
    download_pos: "PO_004.pdf",
  },
  {
    id: 5,
    po_number: "PO/2025-26/005",
    po_date: "10/05/2025",
    vendor_name: "Secure Wrap Co.",
    linked_indents: "IND9020",
    delivery_status: "Delivered",
    po_status: "Partially Received",
    total_amount: 67800,
    download_pos: "PO_005.pdf",
  },

];



export const reorderReportData = [
  {
    id: 1,
    productname: 'Surgical Gloves',
    sku_code: 'PM00456',
    UOM: 'Box',
    current_stock: 290,
    record_level: '1000',
    min_level: 590,
    last_stock_in_date: '2025-05-18',
    last_stock_out_date: '2025-06-05',
    suggested_action: 'Raise Indent',
    status: 'Reorder',
  },
  {
    id: 2,
    productname: 'Face Masks',
    sku_code: 'PM00486',
    UOM: 'Pack',
    current_stock: 599,
    record_level: '2000',
    min_level: 360,
    last_stock_in_date: '2025-04-10',
    last_stock_out_date: '2025-05-30',
    suggested_action: 'Urgent Reorder',
    status: 'SOS',
  },
  {
    id: 3,
    productname: 'Syringes 5ml',
    sku_code: 'PM0856',
    UOM: 'Box',
    current_stock: 660,
    record_level: '500',
    min_level: 40,
    last_stock_in_date: '2025-06-01',
    last_stock_out_date: '2025-06-06',
    suggested_action: 'Stock Sufficient',
    status: 'Healthy',
  },
  {
    id: 4,
    productname: 'IV Cannula',
    sku_code: 'PM00056',
    UOM: 'Box',
    current_stock: 1000,
    record_level: '600',
    min_level: 250,
    last_stock_in_date: '2025-05-25',
    last_stock_out_date: '2025-06-02',
    suggested_action: 'Place Order Soon',
    status: 'Reorder',
  },
  {
    id: 5,
    productname: 'Hand Sanitizer',
    sku_code: 'PM00487',
    UOM: 'Litre',
    current_stock: 200,
    record_level: '560',
    min_level: 10,
    last_stock_in_date: '2025-05-10',
    last_stock_out_date: '2025-06-01',
    suggested_action: 'Raise Indent Immediately',
    status: 'SOS',
  },
];



export const consumptionReportData = [
  {
    id: 1,
    productname: 'A4 Copier Paper',
    sku_code: 'PPR-A4-500',
    total_issued: 1200,
    avg_monthly: 200,
    last_issued: '2025-06-01',
    trend: 'Positive',
  },
  {
    id: 2,
    productname: 'Whiteboard Marker - Blue',
    sku_code: 'MRK-BLU-10',
    total_issued: 340,
    avg_monthly: 60,
    last_issued: '2025-05-29',
    trend: 'Negative',
  },
  {
    id: 3,
    productname: 'Stapler Machine',
    sku_code: 'STP-MCH-01',
    total_issued: 25,
    avg_monthly: 4,
    last_issued: '2025-05-20',
    trend: 'Negative',
  },
  {
    id: 4,
    productname: 'Printer Ink Cartridge - Black',
    sku_code: 'INK-BLK-XL',
    total_issued: 80,
    avg_monthly: 12,
    last_issued: '2025-06-04',
    trend: 'Positive',
  },
  {
    id: 5,
    productname: 'Notepad - Small',
    sku_code: 'NTPD-SML-20',
    total_issued: 500,
    avg_monthly: 75,
    last_issued: '2025-05-30',
    trend: 'Negative',
  },
];



export const indentVsPoData = [
  {
    id: 1,
    indent_number: "IND-2025-001",
    item_name: "Surgical Gloves - Medium",
    requested_quantity: 500,
    approved_quantity: 450,
    po_number: "PO-2025-045",
    po_qty: 450,
    po_status: "Completed",
    department: "General Surgery"
  },
  {
    id: 2,
    indent_number: "IND-2025-002",
    item_name: "IV Set",
    requested_quantity: 300,
    approved_quantity: 300,
    po_number: "PO-2025-046",
    po_qty: 200,
    po_status: "Partial",
    department: "Emergency"
  },
  {
    id: 3,
    indent_number: "IND-2025-003",
    item_name: "Cotton Rolls",
    requested_quantity: 1000,
    approved_quantity: 1000,
    po_number: "PO-2025-047",
    po_qty: 1000,
    po_status: "Completed",
    department: "Orthopedics"
  },
  {
    id: 4,
    indent_number: "IND-2025-004",
    item_name: "Syringes 5ml",
    requested_quantity: 800,
    approved_quantity: 750,
    po_number: "PO-2025-048",
    po_qty: 400,
    po_status: "Partial",
    department: "Pediatrics"
  },
  {
    id: 5,
    indent_number: "IND-2025-005",
    item_name: "Face Masks - N95",
    requested_quantity: 600,
    approved_quantity: 600,
    po_number: "PO-2025-049",
    po_qty: 600,
    po_status: "Completed",
    department: "Anesthesiology"
  }
];
